# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0002_auto_20160622_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cadmin.Status'),
            preserve_default=False,
        ),
    ]
